/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rename

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appLaunches() {
    }
}
