/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package archey

import kotlin.test.Test
import kotlin.test.assertNotNull

class ArcheyTest {
    @Test fun appLaunches() {
        val archey = Archey()
        assertNotNull(archey)
    }
}
