/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package todo.multi.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "App       Demo!"
    }
}
