/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */package business

import kotlin.test.Test
import kotlin.test.assertNotNull

class ModelTest {
    @Test
    fun modelLaunches() {
    }
}
