/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package calc

import calc.Calc
import kotlin.test.Test
import kotlin.test.assertNotNull

class CalcTest {
    @Test
    fun appLaunches() {
        val calc = Calc()
        assertNotNull(calc)
    }

    @Test
    fun addition() {
        val calc = Calc()

        // positive integers
        assert(calc.calculate(0, 0, "+") == 0)
        assert(calc.calculate(100, 0, "+") == 100)
        assert(calc.calculate(0, 100, "+") == 100)
        assert(calc.calculate(100, 100, "+") == 200)

        // negative integers
        assert(calc.calculate(-5, 0, "+") == -5)
        assert(calc.calculate(0, -5, "+") == -5)
    }
}
